---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaotei.
--- DateTime: 2019/5/23 下午6:11
---

window:onClick(function()
    local MLToast = require("LuaComponent.MLToast.MLToast")
    MLToast("你好啊！！！",2,window,-30)
end)


