---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  警告框
---
---@class Alert @parent class
---@public field name string 
---@type Alert
local _class = {
	_priveta_class_name = "Alert"}

---
---  构造方法
---
---@return Alert 
function Alert()
	return _class
end

---
---  设置警告框标题
---
---@param string_a string  标题
---@return Alert 
function _class:title(string_a)
	return self
end

---
---  获取警告框标题
---
---@return string 警告框标题
function _class:title()
	return "string"
end

---
---  设置警告信息
---
---@param string_a string  警告信息
---@return Alert 
function _class:message(string_a)
	return self
end

---
---  获取警告信息
---
---@return string 警告信息
function _class:message()
	return "string"
end

---
---  设置取消按钮文案和回调
---
---@param string_a string  取消按钮文案
---@param callback_b function  点击取消按钮回调
---@return Alert 
function _class:setCancel(string_a, callback_b)
	return self
end

---
---  设置确定按钮文案和回调
---
---@param string_a string  确定按钮文案
---@param callback_b function  点击确定按钮回调
---@return Alert 
function _class:setOk(string_a, callback_b)
	return self
end

---
---  设置多按钮文案和回调
---
---@param array_a Array  多按钮文案
---@param callback_b function  function(idx)...end 
---		 回调被点击按钮索引
---@return Alert 
function _class:setButtonList(array_a, callback_b)
	return self
end

---
---  设置单按钮文案和回调
---
---@param string_a string  按钮文案
---@param callback_b function  点击回调
---@return Alert 
function _class:setSingleButton(string_a, callback_b)
	return self
end

---
---  展示弹框
---
---@return Alert 
function _class:show()
	return self
end

---
---  销毁弹框
---
---@return Alert 
---@version  1.1.35
function _class:dismiss()
	return self
end

return _class