---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  layer动画,作用于视图的layer层,可以用来缩放，位移，旋转等，缩放会按比例改变内容的大小
---
---@note  在iOS端，Animation执行完毕后，不是真实改变尺寸，透明度和位置，若有动画后响应交互事件的需求，需要将alpha或者尺寸调整到终值
---@class Animation @parent class
---@public field name string 
---@type Animation
local _class = {
	_priveta_class_name = "Animation"}

---
---  构造方法
---
---@return Animation 
function Animation()
	return _class
end

---
---  设置X轴方向动画
---
---@param number_a number  from:动画开始X轴位置
---@param number_b number  to:动画结束X轴位置
---@return Animation 
function _class:setTranslateX(number_a, number_b)
	return self
end

---
---  设置Y轴方向动画
---
---@param number_a number  from:动画开始Y轴位置
---@param number_b number  to:动画结束Y轴位置
---@return Animation 
function _class:setTranslateY(number_a, number_b)
	return self
end

---
---  设置旋转动画
---
---@param number_a number  fromDegree:动画起始角度
---@param number_b number  toDegree:动画结束角度
---@return Animation 
---@note  toDegree > fromDegree：顺时针，单位：°
function _class:setRotate(number_a, number_b)
	return self
end

---
---  设置Y轴旋转动画
---
---@param number_a number  fromDegree:动画起始角度
---@param number_b number  toDegree:动画结束角度
---@return Animation 
---@note  toDegree > fromDegree：顺时针，单位：°
function _class:setRotateY(number_a, number_b)
	return self
end

---
---  设置X轴旋转动画
---
---@param number_a number  fromDegree:动画起始角度
---@param number_b number  toDegree:动画结束角度
---@return Animation 
---@note  toDegree > fromDegree：顺时针，单位：°
function _class:setRotateX(number_a, number_b)
	return self
end

---
---  设置X轴缩放动画
---
---@param number_a number  from:动画开始X轴的缩放量
---@param number_b number  to:动画结束X轴的缩放量
---@return Animation 
---@note  1表示默认大小
function _class:setScaleX(number_a, number_b)
	return self
end

---
---  设置Y轴缩放动画
---
---@param number_a number  from:动画开始Y轴的缩放量
---@param number_b number  to:动画结束Y轴的缩放量
---@return Animation 
---@note  1表示默认大小
function _class:setScaleY(number_a, number_b)
	return self
end

---
---  设置透明度动画
---
---@param number_a number  from:动画开始透明度
---@param number_b number  to:动画结束透明度
---@return Animation 
---@note  from, to取值范围:0 ~ 1
function _class:setAlpha(number_a, number_b)
	return self
end

---
---  设置动画重复次数
---
---@param number_a number  -1为无限循环，0为1次，大于1即为总执行次数
---@return Animation 
function _class:repeatCount(number_a)
	return self
end

---
---  设置动画重复方式以及次数
---
---@param number_a number  type:参考[RepeatType](RepeatType.html)，默认不重复
---@param number_b number  count:重复次数,-1为无限重复
---@return Animation 
function _class:setRepeat(number_a, number_b)
	return self
end

---
---  设置动画完成自动复原
---
---@param a boolean  back:是否复原，默认false
---@return Animation 
function _class:setAutoBack(a)
	return self
end

---
---  设置动画时长
---
---@param number_a number  duration:动画时长， 单位s
---@return Animation 
function _class:setDuration(number_a)
	return self
end

---
---  设置动画延时执行时间
---
---@param number_a number  delay:延时时间，单位s
---@return Animation 
function _class:setDelay(number_a)
	return self
end

---
---  设置InterpolatorType
---
---@param number_a number  type:InterpolatorType, 参考[InterpolatorType](InterpolatorType.html)
---@return Animation 
function _class:setInterpolator(number_a)
	return self
end

---
---  开始动画
---
---@param a View  v:动画施加的对象view
---@return Animation 
function _class:start(a)
	return self
end

---
---  暂停动画
---
---@return Animation 
function _class:pause()
	return self
end

---
---  恢复动画
---
---@return Animation 
function _class:resume()
	return self
end

---
---  停止动画
---
---@return Animation 
function _class:stop()
	return self
end

---
---  设置动画开始回调
---
---@param callback_a function  function()...end 
---		 动画开始回调
---@return Animation 
function _class:setStartCallback(callback_a)
	return self
end

---
---  设置动画结束回调
---
---@param callback_a function   回调格式：
---		 ``` 
---		 function(boolean finished)...end 
---		 	  ---finished:动画是正常结束 
---		 end ```
---@return Animation 
function _class:setEndCallback(callback_a)
	return self
end

return _class