---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  应用工具类
---
---@version  1.2.2
---@class Application @parent class
---@public field name string 
---@type Application
Application= {
	_priveta_class_name = "Application"}

---
---  前台切换后台回调
---
---@param callback_a function  function...end 
---		 前台切换后台回调
---@return Application 
---@version  1.2.2
function Application:setForeground2BackgroundCallback(callback_a)
	return self
end

---
---  后台切换前台回调
---
---@param callback_a function  function...end 
---		 后台切换前台回调
---@return Application 
---@version  1.2.2
function Application:setBackground2ForegroundCallback(callback_a)
	return self
end

