---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  BreakMode
---
---@link  https://www.immomo.comBreakMode.html
---@class BreakMode @parent class
---@public field name string 
---@type BreakMode
BreakMode= {
	---
	---  BreakMode
	---
	CLIPPING = "value",

	---
	---  BreakMode
	---
	TAIL = "value",

	---
	---  BreakMode
	---
	HEAD = "value",

	---
	---  BreakMode
	---
	MIDDLE = "value",


}