---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  剪贴板
---
---@class Clipboard @parent class
---@public field name string 
---@type Clipboard
Clipboard= {
	_priveta_class_name = "Clipboard"}

---
---  为粘贴板设置文本，置nil清空
---
---@param string_a string  为粘贴板设置文本，置nil清空
---@return Clipboard 
function Clipboard:setText(string_a)
	return self
end

---
---  获取剪贴板内容
---
---@return Clipboard 
function Clipboard:getText()
	return self
end

