---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  CollectionViewAdapter作为VIew以及该View的数据的桥梁，提供数据项的访问以及为每个数据项创建View
---
---@class CollectionViewAdapter @parent class
---@public field name string 
---@type CollectionViewAdapter
local _class = {
	_priveta_class_name = "CollectionViewAdapter"}

---
---  构造方法
---
---@return CollectionViewAdapter 
function CollectionViewAdapter()
	return _class
end

---
---  设置section数量回调
---
---@param callback_a function  function()...end
---@return CollectionViewAdapter 
function _class:sectionCount(callback_a)
	return self
end

---
---  根据section设置row数量回调
---
---@param callback_a function  function(number section) ... end
---@return CollectionViewAdapter 
function _class:rowCount(callback_a)
	return self
end

---
---  设置不同类型cell的id回调
---
---@param callback_a function  function(number section, number row) ... end 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，reuseId方法与initCellByReusedId、fillCellDataByReuseId等方法配合使用
function _class:reuseId(callback_a)
	return self
end

---
---  根据reuseId设置初始化cell的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell) ... end 
---		 cell: 视图cell
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，此方法与reuseId方法配合使用
function _class:initCellByReuseId(string_a, callback_b)
	return self
end

---
---  根据reuseId设置初始化cell数据的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，此方法与reuseId方法配合使用
function _class:fillCellDataByReuseId(string_a, callback_b)
	return self
end

---
---  设置初始化cell的回调
---
---@param callback_a function  function(table cell) ... end 
---		 cell: 视图cell
---@return CollectionViewAdapter 
---@note  当仅存在一种cell时，使用此方法
function _class:initCell(callback_a)
	return self
end

---
---  设置初始化cell数据的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当仅存在一种cell时，使用此方法
function _class:fillCellData(callback_a)
	return self
end

---
---  根据reuseid设置点击cell的回调
---
---@param string_a string  reuseId: cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:selectedRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置点击cell的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:selectedRow(callback_a)
	return self
end

---
---  设置某个reuseID对应cell的长按回调
---
---
---  设置某个reuseID对应cell的长按回调,触发时长0.5s
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return CollectionViewAdapter 
function _class:longPressRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置cell的长按回调
---
---
---  设置cell的长按回调,触发时长0.5s
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return CollectionViewAdapter 
function _class:longPressRow(callback_a)
	return self
end

---
---  设置cell大小的回调
---
---@param callback_a function  function(number section, number row) ... end 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:sizeForCell(callback_a)
	return self
end

---
---  根据reuseid设置cell大小的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:sizeForCellByReuseId(string_a, callback_b)
	return self
end

---
---  设置cell将要显示的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellWillAppear(callback_a)
	return self
end

---
---  设置cell消失回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellDidDisappear(callback_a)
	return self
end

---
---  设置指定类型cell将要显示的回调
---
---@param string_a string  reuseId:重用Id 
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellWillAppearByReuseId(string_a, callback_b)
	return self
end

---
---  设置指定类型cell消失回调
---
---@param string_a string  reuseId:重用Id 
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellDidDisappearByReuseId(string_a, callback_b)
	return self
end

return _class