---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  指定每个视图之间的间隔以及大小
---
---@note  CollectionViewLayout已废弃, 请使用[CollectionViewGridLayout](CollectionViewGridLayout.html)
---@class CollectionViewLayout @parent class
---@public field name string 
---@type CollectionViewLayout
local _class = {
	_priveta_class_name = "CollectionViewLayout"}

---
---  构造方法
---
---@return CollectionViewLayout 
function CollectionViewLayout()
	return _class
end

---
---  设置cell之间的垂直距离
---
---@param number_a number  cell之间的垂直距离
---@return CollectionViewLayout 
---@note  cell之间的垂直距离，如：竖向滚动，cell行之间的距离；横向滚动，cell列之间的距离
function _class:lineSpacing(number_a)
	return self
end

---
---  获取cell之间的垂直距离
---
---@return number 
---@note  cell之间的水平距离，如：竖向滚动，cell列之间的距离；横向滚动，cell行之间的距离
function _class:lineSpacing()
	return 0
end

---
---  设置cell之间的水平距离
---
---@param number_a number  cell之间的水平距离，如：竖向滚动，cell列之间的距离；横向滚动，cell行之间的距离
---@return CollectionViewLayout 
---@note  cell之间的水平距离，如：竖向滚动，cell列之间的距离；横向滚动，cell行之间的距离
function _class:itemSpacing(number_a)
	return self
end

---
---  获取cell之间的水平距离
---
---@return number 
---@note  cell之间的水平距离，如：竖向滚动，cell列之间的距离；横向滚动，cell行之间的距离
function _class:itemSpacing()
	return 0
end

---
---  设置cell的尺寸
---
---@param a Size  cell 大小
---@return CollectionViewLayout 
function _class:itemSize(a)
	return self
end

---
---  获取cell的尺寸
---
---@return Size 
function _class:itemSize()
	return Size()
end

return _class