---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  编辑框输入方式，提供2种输入模式，默认输入方式和数字输入模式
---
---@link  https://www.immomo.comEditTextViewInputMode.html
---@class EditTextViewInputMode @parent class
---@public field name string 
---@type EditTextViewInputMode
EditTextViewInputMode= {
	---
	---  编辑框输入方式，提供2种输入模式，默认输入方式和数字输入模式
	---
	Normal = "value",

	---
	---  编辑框输入方式，提供2种输入模式，默认输入方式和数字输入模式
	---
	Number = "value",


}