---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  File工具类
---
---@note  静态类
---@class File @parent class
---@public field name string 
---@type File
File= {
	_priveta_class_name = "File"}

---
---  文件是否存在
---
---@param string_a string  path:file路径
---@return boolean true为存在
function File:exist(string_a)
	return true
end

---
---  是否是文件夹
---
---@param string_a string  path:file路径
---@return boolean true是文件夹
function File:isDir(string_a)
	return true
end

---
---  是否是文件
---
---@param string_a string  path:file路径
---@return boolean true是文件
function File:isFile(string_a)
	return true
end

---
---  从数组文件中同步读取内容
---
---@param string_a string  filePath:数组文件路径
---@return Array 
function File:syncReadArray(string_a)
	return Array()
end

---
---  从映射文件中同步读取内容
---
---@param string_a string  filePath:数组文件路径
---@return Map 
function File:syncReadMap(string_a)
	return Map()
end

---
---  从文件中同步读取string
---
---@param string_a string  path:文件路径
---@return string 
function File:syncReadString(string_a)
	return "string"
end

---
---  同步写文件
---
---@param string_a string  path:写入文件路径
---@param string_b string  content: 写入内容
---@return number number 0: 成功, 其他失败
function File:syncWriteFile(string_a, string_b)
	return 0
end

---
---  将map内容同步写入文件
---
---@param string_a string  path:写入文件路径
---@param map_b Map  conent:写入内容
---@return number number 0: 成功, 其他失败
function File:syncWriteMap(string_a, map_b)
	return 0
end

---
---  将array内容同步写入文件
---
---@param string_a string  path:写入文件路径
---@param array_b Array  array:写入内容
---@return number number 0: 成功, 其他失败
function File:syncWriteArray(string_a, array_b)
	return 0
end

---
---  同步解压文件
---
---@param string_a string  source:待解压文件路径
---@param string_b string  targetPath:解压目的路径
---@return number number 0: 成功, 其他失败
function File:syncUnzipFile(string_a, string_b)
	return 0
end

---
---  从资源文件中读取文件内容
---
---@param string_a string  filePath:文件路径
---@return string 文件内容
function File:syncReadTextFromAsset(string_a)
	return "string"
end

---
---  向资源文件中写入内容
---
---@param string_a string  filePath:文件路径
---@param string_b string  content:写入内容
---@return number true: 写入文件成功，false：写入文件失败
function File:syncWriteTextToAsset(string_a, string_b)
	return 0
end

---
---  异步解压文件
---
---@param string_a string  sourcePath:待解压文件路径
---@param string_b string  target:解压目的路径
---@param callback_c function  function(number code,String sourcePath)...end 
---		 code:解压结果，0 成功，其他失败 
---		 sourcePath:待解压文件路径
---@return File 
function File:asyncUnzipFile(string_a, string_b, callback_c)
	return self
end

---
---  异步写Array到文件中
---
---@param string_a string  path:写入文件路径
---@param array_b Array  content:写入文件内容
---@param callback_c function  function(number code,String sourcePath)...end 
---		 code:解压结果，0 成功，其他失败 
---		 sourcePath:待解压文件路径
---@return File 
function File:asyncWriteArray(string_a, array_b, callback_c)
	return self
end

---
---  异步写Map到文件中
---
---@param string_a string  path:写入文件路径
---@param map_b Map  content:写入文件内容
---@param callback_c function  function(number code,String sourcePath)...end 
---		 code:解压结果，0 成功，其他失败 
---		 sourcePath:待解压文件路径
---@return File 
function File:asyncWriteMap(string_a, map_b, callback_c)
	return self
end

---
---  异步写string到文件中
---
---@param string_a string  path:写入文件路径
---@param string_b string  content:写入内容
---@param callback_c function  function(number code, String path)...end 
---		 code:写入状态，0: 成功, 其他失败 
---		 path:写入路径
---@return File 
function File:asyncWriteFile(string_a, string_b, callback_c)
	return self
end

---
---  异步读取文件
---
---@param a <#type#>  path:文件路径
---@param b <#type#>  function(number code, string fileContent)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 fileContent:读取的文件内容
---@return File 
function File:asyncReadFile(a, b)
	return self
end

---
---  异步读取Map文件内容
---
---@param string_a string  path:文件路径
---@param callback_b function  function(number code, Map map)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 map:读取内容
---@return File 
function File:asyncReadMapFile(string_a, callback_b)
	return self
end

---
---  异步读取数组文件内容
---
---@param string_a string  path:文件路径
---@param callback_b function  function(number code, Array array)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 array:读取内容
---@return File 
function File:asyncReadArrayFile(string_a, callback_b)
	return self
end

---
---  获取MLN存储主目录
---
---@return File 
---@version  1.2.11
function File:getStorageDir()
	return self
end

---
---  创建文件
---
---@param string_a string  path:文件路径
---@param callback_b function  function(number code, string filePath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 filePath:文件路径
---@return File 
---@version  1.2.11
function File:asyncCreateFile(string_a, callback_b)
	return self
end

---
---  创建文件夹
---
---@param string_a string  path:文件夹路径
---@param callback_b function  function(number code, string dirPath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 dirPath:文件夹路径
---@return File 
---@version  1.2.11
function File:asyncCreateDirs(string_a, callback_b)
	return self
end

---
---  删除文件/文件夹
---
---@param string_a string  path:文件/文件夹路径
---@param callback_b function  function(number code, string dirPath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 path:文件/文件夹路径
---@return File 
---@version  1.2.11
function File:asyncDelete(string_a, callback_b)
	return self
end

---
---  移动文件/文件夹
---
---@param string_a string  srcPath:源文件路径
---@param string_b string  dstPath:目标文件路径
---@param callback_c function  function(number code, string srcPath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 srcPath:源文件/文件夹路径
---@return File 
---@version  1.2.11
function File:asyncMoveFile(string_a, string_b, callback_c)
	return self
end

---
---  拷贝文件/文件夹
---
---@param string_a string  srcPath:源文件路径
---@param string_b string  dstPath:目标文件路径
---@param callback_c function  function(number code, string srcPath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 srcPath:源文件/文件夹路径
---@return File 
---@version  1.2.11
function File:asyncCopyFile(string_a, string_b, callback_c)
	return self
end

---
---  获取指定文件夹下所有文件/文件夹
---
---@param string_a string  srcPath:源文件路径
---@param b boolean  recursive:是否递归遍历子项
---@param callback_c function  function(number code, string srcPath)...end 
---		 code:读取状态，0: 成功, 其他失败 
---		 array:包含该文件夹下所有项的数组
---@return File 
---@version  1.2.11
function File:asyncGetFileList(string_a, b, callback_c)
	return self
end

---
---  获取文件属性
---
---@param string_a string  filePath:文件路径
---@return Map 返回文件属性Map, 文件大小：FileInfo.FileSize, 修改时间：FileInfo.ModiDate
---@version  1.2.11
function File:getFileInfo(string_a)
	return Map()
end

