---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  可支持普通移动，缩放，透明渐变动画，或组合， 会改变View的frame
---
---@version  1.1.2
---@class FrameAnimation @parent class
---@public field name string 
---@type FrameAnimation
local _class = {
	_priveta_class_name = "FrameAnimation"}

---
---  构造方法
---
---@return FrameAnimation 
---@version  1.1.2
function FrameAnimation()
	return _class
end

---
---  直接设置x的值，x从from点移动到to点, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  to:动画结束的x值
---@return FrameAnimation 
---@version  1.1.2
function _class:setTranslateXTo(number_a)
	return self
end

---
---  直接设置x的值，x从from点移动到to点, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  from:动画起始x值
---@param number_b number  to:动画结束x值
---@return FrameAnimation 
---@version  1.1.2
function _class:setTranslateX(number_a, number_b)
	return self
end

---
---  直接设置y的值，y从from点移动到to点, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  to:动画结束的y值
---@return FrameAnimation 
---@version  1.1.2
function _class:setTranslateYTo(number_a)
	return self
end

---
---  直接设置y的值，y从from点移动到to点, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  from:动画起始y值
---@param number_b number  to:动画结束y值
---@return FrameAnimation 
---@version  1.1.2
function _class:setTranslateY(number_a, number_b)
	return self
end

---
---  直接设置width的值，width从当前宽度动画到to宽度, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  to:动画结束的宽度
---@return FrameAnimation 
---@version  1.1.2
function _class:setScaleWidthTo(number_a)
	return self
end

---
---  直接设置width的值，width从当前宽度动画到to宽度, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  from:动画起始宽度
---@param number_b number  to:动画结束宽度
---@return FrameAnimation 
---@version  1.1.2
function _class:setScaleWidth(number_a, number_b)
	return self
end

---
---  直接设置height的值，height从当前高度动画到to高度, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  to:动画结束的高度
---@return FrameAnimation 
---@version  1.1.2
function _class:setScaleHeightTo(number_a)
	return self
end

---
---  直接设置height的值，height从当前高度动画到to高度, 数值为ValueType.CURRENT时，代表当前
---
---@param number_a number  from:动画起始高度
---@param number_b number  to:动画结束高度
---@return FrameAnimation 
---@version  1.1.2
function _class:setScaleHeight(number_a, number_b)
	return self
end

---
---  设置透明度动画
---
---@param number_a number  to:动画结束透明度, to取值范围:0.0 ~ 1.0
---@return FrameAnimation 
---@version  1.1.2
function _class:setAlphaTo(number_a)
	return self
end

---
---  设置透明度动画
---
---@param number_a number  from:动画起始透明度, from取值范围:0.0 ~ 1.0
---@param number_b number  to:动画结束透明度, to取值范围:0.0 ~ 1.0
---@return FrameAnimation 
---@version  1.1.2
function _class:setAlpha(number_a, number_b)
	return self
end

---
---  设置背景动画
---
---@param a Color  to:动画结束背景颜色
---@return FrameAnimation 
---@version  1.1.2
function _class:setBgColorTo(a)
	return self
end

---
---  to:动画结束背景颜色
---
---@param a Color  from:动画起始背景颜色
---@param b Color  to:动画结束背景颜色
---@return FrameAnimation 
---@version  1.1.2
function _class:setBgColor(a, b)
	return self
end

---
---  设置动画时长
---
---@param number_a number  duration:时长，单位s
---@return FrameAnimation 
function _class:setDuration(number_a)
	return self
end

---
---  设置动画延时时间
---
---@param number_a number  delay:延时时间
---@return FrameAnimation 
---@version  1.1.2
function _class:setDelay(number_a)
	return self
end

---
---  设置重复次数
---
---@param number_a number  动画播放次数,-1为无限循环，0为1次，大于1即为总执行次数
---@return FrameAnimation 
---@version  1.2.1
function _class:repeatCount(number_a)
	return self
end

---
---  开启动画无限重复，从开始位置重复动画
---
---@return FrameAnimation 
---@note  开启后无法停止
---@version  1.1.2
function _class:needRepeat()
	return self
end

---
---  开启动画无限重复，从结束位置反向重复动画
---
---@return FrameAnimation 
---@note  开启后无法停止
---@version  1.1.2
function _class:needAutoreverseRepeat()
	return self
end

---
---  设置InterpolatorType
---
---@param number_a number  type: 见[InterpolatorType](InterpolatorType.html)
---@return FrameAnimation 
---@version  1.1.2
function _class:setInterpolator(number_a)
	return self
end

---
---  开始动画
---
---@param a View  v:动画施加的对象view
---@return FrameAnimation 
---@version  1.1.2
function _class:start(a)
	return self
end

---
---  设置动画结束回调
---
---@param a boolean  isFinished:标记动画是否完整执行
---@return FrameAnimation 
---@version  1.1.2
function _class:setEndCallback(a)
	return self
end

return _class