---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  视图组件的重力吸附枚举
---
---
---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
---
---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
---@link  https://www.immomo.comGravity.html
---@class Gravity @parent class
---@public field name string 
---@type Gravity
Gravity= {
	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	BOTTOM = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	CENTER_HORIZONTAL = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	CENTER_VERTICAL = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	CENTER = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	LEFT = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	TOP = "value",

	---
	---  视图组件的重力吸附枚举
	---
	---
	---  当视图设置重力吸附方向时，则该视图位于父视图的对应方向上，重力效果可以通过‘或’运算组合
	---
	---@note  在LinearLayout中重力吸附效果特殊，具体请参考[Lua基础布局简介](Lua基础布局简介.html)
	RIGHT = "value",


}