---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  加载指示器
---
---@note  对应iOS原生UIActivityIndicatorView控件
---@class Loading @parent class
---@public field name string 
---@type Loading
Loading= {
	_priveta_class_name = "Loading"}

---
---  显示加载指示器
---
---@return Loading 
function Loading:show()
	return self
end

---
---  隐藏加载指示器
---
---@return Loading 
function Loading:hide()
	return self
end

