---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  页面跳转工具
---
---
---  此工具会根据传递的参数跳转或者关闭指定页面
---
---@class Navigator @parent class
---@public field name string 
---@type Navigator
Navigator= {
	_priveta_class_name = "Navigator"}

---
---  界面跳转
---
---
---  根据页面的主要描述信息跳转到指定页面，并携带附带参数
---
---@param string_a string  跳转页面需要的主要描述信息
---@param map_b Map  跳转页面需要的附带参数，此参数为预留字段，不需要时可传nil
---@param c AnimType  指定跳转的动画类型，详情参考[AnimType](AnimType.html)
---@return Navigator 
function Navigator:gotoPage(string_a, map_b, c)
	return self
end

---
---  跳转指定界面同时关闭当前页面
---
---
---  根据页面的主要描述信息跳转到指定页面，关闭当前页面，并携带附带参数
---
---@param string_a string  跳转页面需要的主要描述信息
---@param map_b Map  跳转页面需要的附带参数，此参数为预留字段，不需要时可传nil
---@param c AnimType  指定跳转的动画类型，详情参考[AnimType](AnimType.html)
---@return Navigator 
function Navigator:gotoAndCloseSelf(string_a, map_b, c)
	return self
end

---
---  关闭当前页面
---
---@param a AnimType  指定跳转的动画类型，详情参考[AnimType](AnimType.html)
---@return Navigator 
function Navigator:closeSelf(a)
	return self
end

---
---  返回到某个指定lua页
---
---
---  可以关闭一个或多个lua页面，如果找不到指定页面就会失败
---
---@param string_a string  指定页面的标志符
---@return boolean true 代表跳转成功，false 代表跳转失败（如未找到该页面就跳转失败等)
---@note  默认倒序查找
function Navigator:closeToLuaPageFinished(string_a)
	return true
end

