---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  网络状态
---
---@link  https://www.immomo.comNetworkState.html
---@class NetworkState @parent class
---@public field name string 
---@type NetworkState
NetworkState= {
	---
	---  网络状态
	---
	WIFI = "value",

	---
	---  网络状态
	---
	CELLULAR = "value",

	---
	---  网络状态
	---
	NO_NETWORK = "value",

	---
	---  网络状态
	---
	UNKNOWN = "value",


}