---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  代表圆角位置的枚举
---
---@link  https://www.immomo.comRectCorner.html
---@class RectCorner @parent class
---@public field name string 
---@type RectCorner
RectCorner= {
	---
	---  代表圆角位置的枚举
	---
	BOTTOM_LEFT = "value",

	---
	---  代表圆角位置的枚举
	---
	ALL_CORNERS = "value",

	---
	---  代表圆角位置的枚举
	---
	TOP_RIGHT = "value",

	---
	---  代表圆角位置的枚举
	---
	BOTTOM_RIGHT = "value",

	---
	---  代表圆角位置的枚举
	---
	TOP_LEFT = "value",


}