---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  提供网络响应体中一些特殊的Key
---
---@link  https://www.immomo.comResponseKey.html
---@class ResponseKey @parent class
---@public field name string 
---@type ResponseKey
ResponseKey= {
	---
	---  提供网络响应体中一些特殊的Key
	---
	Cache = "value",

	---
	---  提供网络响应体中一些特殊的Key
	---
	Path = "value",


}