---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  键盘返回键样式
---
---
---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
---
---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
---@link  https://www.immomo.comReturnType.html
---@class ReturnType @parent class
---@public field name string 
---@type ReturnType
ReturnType= {
	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Send = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Next = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Done = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Default = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Go = "value",

	---
	---  键盘返回键样式
	---
	---
	---  主要用于输入框进入编辑模式后，键盘的返回键位置，显示的文本样式
	---
	---@note  主要用于输入框等组件，详情见[EditTextView](EditTextView.html)
	Search = "value",


}