---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  尺寸
---
---@class Size @parent class
---@public field name string 
---@type Size
local _class = {
	_priveta_class_name = "Size"}

---
---  构造方法
---
---@param number_a number  w: 宽度
---@param number_b number  h: 高度
---@return Size 
function Size(number_a, number_b)
	return _class
end

---
---  设置宽度
---
---@param number_a number  宽度
---@return Size 
function _class:width(number_a)
	return self
end

---
---  获取宽度
---
---@return number 
function _class:width()
	return 0
end

---
---  设置高度
---
---@param number_a number  高度
---@return Size 
function _class:height(number_a)
	return self
end

---
---  获取高度
---
---@return number 
function _class:height()
	return 0
end

return _class