---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  状态栏样式，提供2种风格，深色风格和浅色风格，默认深色风格
---
---@link  https://www.immomo.comStatusBarStyle.html
---@class StatusBarStyle @parent class
---@public field name string 
---@type StatusBarStyle
StatusBarStyle= {
	---
	---  状态栏样式，提供2种风格，深色风格和浅色风格，默认深色风格
	---
	Default = "value",

	---
	---  状态栏样式，提供2种风格，深色风格和浅色风格，默认深色风格
	---
	Light = "value",


}