---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  用于自适应Cell高度。需要配合自动布局使用
---
---@note  在init和fillData时候布局尽量不要获取cell.contentView的宽高，因为这时候有可能是不准确的
---@class TableViewAutoFitAdapter @parent class
---@public field name string 
---@type TableViewAutoFitAdapter
local _class = {
	_priveta_class_name = "TableViewAutoFitAdapter"}

---
---  构造方法
---
---
---  初始化一个适配器对象
---
---@return TableViewAutoFitAdapter 
function TableViewAutoFitAdapter()
	return _class
end

---
---  根据复用ID回调高度
---
---@param string_a string  reuseID:复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number row) 
---		 	 ---cell：视图cell 
---		 	 ---row：视图页数 
---		 end ```
---@return TableViewAutoFitAdapter 
function _class:heightForCellByReuseId(string_a, callback_b)
	return self
end

---
---  设置组数回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function() 
---		 	 ---在回调中返回组数，默认为1 
---		 end ```
---@return TableViewAdapter 
---@note  该方法不设置，默认组数为1
function _class:sectionCount(callback_a)
	return self
end

---
---  设置行数回调
---
---
---  根据组数返回对应的行数
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section) 
---		 	 ---section:组数，根据组数返回对应的行数 
---		 end ```
---@return TableViewAdapter 
function _class:rowCount(callback_a)
	return self
end

---
---  设置回调复用ID
---
---
---  根据组数和行数返回对应cell的复用ID
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section,number row) 
---		 	 ---section：组数 
---		 	 ---row：行数  
---		 	 ---返回复用ID，string 
---		 end ```
---@return TableViewAdapter 
---@note  使用该方法需要配合initCellByReuseId和fillCellDataByReuseId方法,默认id写法与此方法不要同时使用
function _class:reuseId(callback_a)
	return self
end

---
---  设置初始化cell的回调
---
---
---  根据复用ID，组数和行数进行初始化cell的回调
---
---@param string_a string  reuseID：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 end ```
---@return TableViewAdapter 
---@note  使用该方法，配合fillCellDataByReuseId和reuseId方法
function _class:initCellByReuseId(string_a, callback_b)
	return self
end

---
---  设置进行数据赋值的回调
---
---
---  根据复用ID，组数和行数进行cell的数据赋值操作
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
---@note  使用该方法，配合reuseId和initCellByReuseId方法
function _class:fillCellDataByReuseId(string_a, callback_b)
	return self
end

---
---  设置初始化cell的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 end ```
---@return TableViewAdapter 
function _class:initCell(callback_a)
	return self
end

---
---  设置cell赋值的回调
---
---
---  根据cell，组数和行数对cell进行赋值操作
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
function _class:fillCellData(callback_a)
	return self
end

---
---  点击了某行
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
function _class:selectedRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置点击cell的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
function _class:selectedRow(callback_a)
	return self
end

---
---  设置某个reuseID对应cell的长按回调
---
---
---  设置某个reuseID对应cell的长按回调，触发时长0.5s
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
function _class:longPressRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置cell的长按回调
---
---
---  设置cell的长按回调，触发时长0.5s
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
function _class:longPressRow(callback_a)
	return self
end

---
---  设置返回某行的高度的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section,number row) 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 	 ---返回高度,number 
---		 end ```
---@return TableViewAdapter 
function _class:heightForCell(callback_a)
	return self
end

---
---  设置返回某行的高度的回调
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(number section,number row) 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 	 ---返回高度,number 
---		 end ```
---@return TableViewAdapter 
function _class:heightForCellByReuseId(string_a, callback_b)
	return self
end

---
---  cell将要展示的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
---@note  iOS端会在刚刚展示的时候就调用，Android会在完全展示后调用
function _class:cellWillAppear(callback_a)
	return self
end

---
---  cell已经消失后的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
---@note  注意时机问题，即该回调的调用时机是cell已经消失
function _class:cellDidDisappear(callback_a)
	return self
end

---
---  cell将要展示时的回调
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
---@note  需配合reuseId方法使用，iOS端会在刚刚展示的时候就调用，Android会在完全展示后调用
function _class:cellWillAppearByReuseId(string_a, callback_b)
	return self
end

---
---  cell已经消失后的回调
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return TableViewAdapter 
---@note  需配合reuseId方法使用
function _class:cellDidDisappearByReuseId(string_a, callback_b)
	return self
end

---
---  点击Cell后高亮
---
---@param a boolean  是否开启，默认关闭
---@return TableViewAdapter 
function _class:showPressed(a)
	return self
end

---
---  获取是否开启了高亮效果
---
---@return boolean 布尔值
function _class:showPressed()
	return true
end

---
---  点击后的高亮颜色
---
---@param a Color  设置cell点击后的高亮颜色
---@return TableViewAdapter 
function _class:pressedColor(a)
	return self
end

---
---  获取高亮颜色
---
---@return Color 色值
function _class:pressedColor()
	return Color()
end

return _class