---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  TabSegmentView的标签布局样式
---
---@note  默认居左，可以设置为居中，居右不常用
---@version  1.1.8
---@link  https://www.immomo.comTabSegmentAlignment.html
---@class TabSegmentAlignment @parent class
---@public field name string 
---@type TabSegmentAlignment
TabSegmentAlignment= {
	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	---@version  1.1.8
	CENTER = "value",

	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	---@version  1.1.8
	RIGHT = "value",

	---
	---  TabSegmentView的标签布局样式
	---
	---@note  默认居左，可以设置为居中，居右不常用
	---@version  1.1.8
	LEFT = "value",


}