---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  弱文本提示
---
---@class Toast @parent class
---@public field name string 
---@type Toast
local _class = {
	_priveta_class_name = "Toast"}

---
---  文本提示类方法
---
---
---  弱提示，在网络请求失败，用户做了某些操作后弹出，自动消失，不影响其他的操作
---
---@param string_a string  msg：提示内容
---@param number_b number  duration：单位s，提示时长
---@return Toast 
function Toast(string_a, number_b)
	return _class
end

return _class