---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  StyleString下划线样式
---
---
---  StyleString下划线样式
---
---@link  https://www.immomo.comUnderlineStyle.html
---@class UnderlineStyle @parent class
---@public field name string 
---@type UnderlineStyle
UnderlineStyle= {
	---
	---  StyleString下划线样式
	---
	---
	---  StyleString下划线样式
	---
	LINE = "value",

	---
	---  StyleString下划线样式
	---
	---
	---  StyleString下划线样式
	---
	NONE = "value",


}