---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  控制瀑布流样式
---
---
---  可以通过设置属性来控制瀑布流的行间距列间距以及列数
---
---@class WaterfallLayout @parent class
---@public field name string 
---@type WaterfallLayout
local _class = {
	_priveta_class_name = "WaterfallLayout"}

---
---  构造方法
---
---
---  构造方法，返回实例对象
---
---@return WaterfallLayout 返回实例
function WaterfallLayout()
	return _class
end

---
---  设置列数
---
---@param number_a number  列数
---@return WaterfallLayout 
function _class:spanCount(number_a)
	return self
end

---
---  获取列数
---
---
---  返回当前设置的有几列
---
---@return number 返回列数
function _class:spanCount()
	return 0
end

---
---  设置行间距
---
---
---  设置行间距，即垂直方向cell之间的距离
---
---@param number_a number  行间距值
---@return WaterfallLayout 
function _class:lineSpacing(number_a)
	return self
end

---
---  获取行间距
---
---
---  获取行间距值
---
---@return number 行间距值
function _class:lineSpacing()
	return 0
end

---
---  设置列间距
---
---
---  设置列间距，即水平方向cell之间的距离
---
---@param number_a number  列间距值
---@return WaterfallLayout 
function _class:itemSpacing(number_a)
	return self
end

---
---  获取列间距
---
---
---  获取列间距值
---
---@return number 列间距值
function _class:itemSpacing()
	return 0
end

return _class