---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 31-07-2019 18:47
---

---
---  数据源及事件回调适配器
---
---
---  数据源方法
---
---@note  继承了CollectionViewAdapter所有方法
---@class WaterfallAdapter @parent class
---@public field name string 
---@type WaterfallAdapter
local _class = {
	_priveta_class_name = "WaterfallAdapter"}

---
---  构造方法
---
---
---  返回适配器的实例对象
---
---@return WaterfallAdapter 
function WaterfallAdapter()
	return _class
end

---
---  设置初始化Header的回调
---
---@param callback_a function  function(table header) ... end 
---		 header: 视图header, 类型为Lua中的table，表中仅存在一个元素contentView
---@return WaterfallAdapter 
---@note  WaterfallView 只有一个header
function _class:initHeader(callback_a)
	return self
end

---
---  设置初始化header数据的回调
---
---@param callback_a function  function(table header, number section, number row) ... end 
---		 header: 视图header, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 section&row:header的section以及row
---@return WaterfallAdapter 
---@note  WaterfallView 只有一个header
function _class:fillHeaderData(callback_a)
	return self
end

---
---  回调header高度
---
---
---  回调首个header高度，WaterfallView只能有一个header
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section) 
---		 	 ---section: 分组数 
---		  end ```
---@return WaterfallAdapter 
---@note  用的时候记得这些参数索引都是从1开始
function _class:heightForHeader(callback_a)
	return self
end

---
---  回调header是否有效
---
---
---  回调首个header高度，WaterfallView只能有一个header
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section) 
---		 	 ---section: 分组数 
---		  	 return true or false 
---		 end ```
---@return WaterfallAdapter 
function _class:headerValid(callback_a)
	return self
end

---
---  回调cell高度
---
---
---  根据组数和行数，回调每个Item的高度
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(number section, number row) 
---		 	 ---section: 分组数 
---		 	 ---row:行数 
---		 end ```
---@return WaterfallAdapter 
---@note  用的时候记得这些参数索引都是从1开始
function _class:heightForCell(callback_a)
	return self
end

---
---  header视图将要显示的回调
---
---
---  header将要展示时候的回调，回调没有任何参数
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function() 
---		 end ```
---@return WaterfallAdapter 
function _class:headerWillAppear(callback_a)
	return self
end

---
---  header已经消失的回调
---
---
---  header已经消失的回调
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function() 
---		 end ```
---@return WaterfallAdapter 
function _class:headerDidDisappear(callback_a)
	return self
end

---
---  设置section数量回调
---
---@param callback_a function  function()...end
---@return CollectionViewAdapter 
function _class:sectionCount(callback_a)
	return self
end

---
---  根据section设置row数量回调
---
---@param callback_a function  function(number section) ... end
---@return CollectionViewAdapter 
function _class:rowCount(callback_a)
	return self
end

---
---  设置不同类型cell的id回调
---
---@param callback_a function  function(number section, number row) ... end 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，reuseId方法与initCellByReusedId、fillCellDataByReuseId等方法配合使用
function _class:reuseId(callback_a)
	return self
end

---
---  根据reuseId设置初始化cell的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell) ... end 
---		 cell: 视图cell
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，此方法与reuseId方法配合使用
function _class:initCellByReuseId(string_a, callback_b)
	return self
end

---
---  根据reuseId设置初始化cell数据的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当存在多种类型cell时，此方法与reuseId方法配合使用
function _class:fillCellDataByReuseId(string_a, callback_b)
	return self
end

---
---  设置初始化cell的回调
---
---@param callback_a function  function(table cell) ... end 
---		 cell: 视图cell
---@return CollectionViewAdapter 
---@note  当仅存在一种cell时，使用此方法
function _class:initCell(callback_a)
	return self
end

---
---  设置初始化cell数据的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
---@note  当仅存在一种cell时，使用此方法
function _class:fillCellData(callback_a)
	return self
end

---
---  根据reuseid设置点击cell的回调
---
---@param string_a string  reuseId: cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:selectedRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置点击cell的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:selectedRow(callback_a)
	return self
end

---
---  设置某个reuseID对应cell的长按回调
---
---
---  设置某个reuseID对应cell的长按回调,触发时长0.5s
---
---@param string_a string  reuseId：复用ID
---@param callback_b function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return CollectionViewAdapter 
function _class:longPressRowByReuseId(string_a, callback_b)
	return self
end

---
---  设置cell的长按回调
---
---
---  设置cell的长按回调,触发时长0.5s
---
---@param callback_a function  回调格式：
---		 ``` 
---		 function(table cell,number section,number row) 
---		 	 ---cell：cell视图表, 类型为Lua中的table，表中仅存在一个元素contentView 
---		 	 ---section：组数 
---		 	 ---row：行数 
---		 end ```
---@return CollectionViewAdapter 
function _class:longPressRow(callback_a)
	return self
end

---
---  设置cell大小的回调
---
---@param callback_a function  function(number section, number row) ... end 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:sizeForCell(callback_a)
	return self
end

---
---  根据reuseid设置cell大小的回调
---
---@param string_a string  reuseId:cell类型
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:sizeForCellByReuseId(string_a, callback_b)
	return self
end

---
---  设置cell将要显示的回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellWillAppear(callback_a)
	return self
end

---
---  设置cell消失回调
---
---@param callback_a function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellDidDisappear(callback_a)
	return self
end

---
---  设置指定类型cell将要显示的回调
---
---@param string_a string  reuseId:重用Id 
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellWillAppearByReuseId(string_a, callback_b)
	return self
end

---
---  设置指定类型cell消失回调
---
---@param string_a string  reuseId:重用Id 
---@param callback_b function  function(table cell, number section, number row) ... end 
---		 cell: 视图cell 
---		 section&row:cell的section以及row
---@return CollectionViewAdapter 
function _class:cellDidDisappearByReuseId(string_a, callback_b)
	return self
end

return _class