---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2019/11/10 上午11:29
---



--label = Label()
--label:setGravity(Gravity.CENTER)
--label:text("Hello World!")
--window:addView(label)

--点击屏幕，弹Toast Demo
--require("LuaComponent.MLToast.MLToastDemo")

