---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 14-01-2020 17:53
---

---
---  ScrollView滚动方向
---
---@link  https://www.immomo.comScrollDirection.html
---@class ScrollDirection @parent class
---@public field name string 
---@type ScrollDirection
ScrollDirection= {
	---
	---  ScrollView滚动方向
	---
	VERTICAL = "value",

	---
	---  ScrollView滚动方向
	---
	HORIZONTAL = "value",


}